# -*- coding: utf-8 -*-
"""Cati.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHAeAK-TeyHjPVSqJ6KpH5KKPdGV3_je
"""

import os

os.environ["KAGGLE_USERNAME"] = "eduardosanzovo"
os.environ["KAGGLE_KEY"] = "b0ac345c494d78f627436504dbf3933a"

!pip install -q kaggle
!kaggle competitions download -c house-prices-advanced-regression-techniques
!unzip -o house-prices-advanced-regression-techniques.zip

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_train.head()

df_train.info()

df_train.drop_duplicates()

nulos = df_train.isna().sum()
print(nulos[nulos > 0])

df_lot = df_train[["LotArea", "LotConfig", "LotFrontage"]]

df_lot = df_lot.dropna()
df_lot = pd.get_dummies(df_lot, columns=["LotConfig"])

y = df_lot["LotFrontage"]
x = df_lot.drop("LotFrontage", axis=1)

model = LinearRegression()
model.fit(x, y)

df_train["LotFrontage"] = df_train["LotFrontage"].fillna(model.predict(df_train[["LotArea", "LotConfig"]]))