# -*- coding: utf-8 -*-
"""Semana2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIkbhMLLrdvgf5cJltSEd4kc99YjENyt

##1. Bibliotecas
"""

from google.colab import drive
import pandas as pd
import sqlite3

"""## 2. Drive"""

drive.mount('/content/drive')

"""##3. Importe do arquivo + head"""

df = pd.read_csv('/content/drive/MyDrive/ipl/ipl_data.csv')

print(df.head(3))

"""## 4. Info"""

print(df.info())

"""## 5. Describe"""

print(df.describe())

"""### 6. Loc"""

print(df.loc[200])

"""## 7. Removendo duplicatas"""

# tamanho original
print(f"tamanho original: {df.shape}")

# removeu 25 linhas com valores nulos
df = df.dropna()

# tamanho novo
print(f"tamanho novo: {df.shape}")

"""## 8. SQL + Queries"""

df2 = pd.read_csv('/content/drive/MyDrive/ipl/ipl_comprehensive_dataset.csv')

# adicionando match number no primeiro dataframe para ser possível fazer join no futuro
df = pd.concat([df, df2['match_number']], axis = 1)

conn = sqlite3.connect(':memory:')

df.to_sql ("data", conn, index = False , if_exists = "replace")

df2.to_sql ("match", conn, index = False , if_exists = "replace")

# Linhas em que Kolkata Knight Riders ganharam
pd.read_sql_query("SELECT winner FROM data WHERE winner = 'Kolkata Knight Riders'", conn)

# cidades que apareceram mais de 30 vezes, ordenadas pelo total de forma decrescente
pd.read_sql_query("SELECT city, COUNT(*) as total FROM data GROUP BY city having total > 30 ORDER BY total DESC", conn)

# join a partir do match number
pd.read_sql_query("SELECT data.season, data.city FROM data JOIN match ON data.match_number = match.match_number", conn)