# -*- coding: utf-8 -*-
"""Cati.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XHAeAK-TeyHjPVSqJ6KpH5KKPdGV3_je

## 1. Importação das Bibliotecas e Dataset
"""

import category_encoders as ce
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Dataset
df_train = pd.read_csv(r"C:\Users\eduqu\Downloads\train.csv")
df_train.head()

df_train.info()

# Removendo duplicatas e a coluna ID (inútil para ajudar na dedução do SalePrice)
df_train.drop_duplicates()
df_train.drop("Id", axis=1, inplace=True)

# LotFrontage = c1·LotConfig + c2·sqrt(LotArea) + c3
df_lot = df_train[["LotArea", "LotConfig", "LotFrontage"]].copy()

df_lot = df_lot.dropna()

min_area = df_lot["LotArea"].min()
max_area = df_lot["LotArea"].max()

df_lot["LotArea"] = (df_lot["LotArea"] - min_area) / (max_area - min_area)
df_lot["sqrt_LotArea"] = np.sqrt(df_lot["LotArea"])

df_lot = pd.get_dummies(df_lot, columns=["LotConfig"])

y = df_lot["LotFrontage"]
x = df_lot.drop(["LotFrontage", "LotArea"], axis=1)

model = LinearRegression()
model.fit(x, y)

missing_mask = df_train["LotFrontage"].isna()
df_missing = df_train.loc[missing_mask, ["LotArea", "LotConfig"]].copy()

df_missing["LotArea"] = (df_missing["LotArea"] - min_area) / (max_area - min_area)
df_missing["sqrt_LotArea"] = np.sqrt(df_missing["LotArea"])

df_missing = pd.get_dummies(df_missing, columns=["LotConfig"])

df_missing = df_missing.drop("LotArea", axis=1)
df_missing = df_missing.reindex(columns=x.columns, fill_value=0)

predicted_values = model.predict(df_missing)

df_train.loc[missing_mask, "LotFrontage"] = predicted_values

# Alley
df_train["Alley"] = df_train["Alley"].fillna("No alley access")

# MasVnrType
df_train["MasVnrType"] = np.where(df_train["MasVnrArea"] == 0, "No masonry", df_train["MasVnrType"])

# Basement
df_train["BsmtQual"] = df_train["BsmtQual"].fillna("No Basement")
df_train["BsmtCond"] = df_train["BsmtCond"].fillna("No Basement")
df_train["BsmtExposure"] = df_train["BsmtExposure"].fillna("No Basement")
df_train["BsmtFinType1"] = df_train["BsmtFinType1"].fillna("No Basement")
df_train["BsmtFinType2"] = df_train["BsmtFinType2"].fillna("No Basement")

# Electrical
df_train["Electrical"] = df_train["Electrical"].fillna(df_train["Electrical"].mode()[0])

# Fireplace
df_train["FireplaceQu"] = df_train["FireplaceQu"].fillna("No Fireplace")

# Garage
df_train["GarageType"] = df_train["GarageType"].fillna("No Garage")
df_train["GarageYrBlt"] = df_train["GarageYrBlt"].fillna(0)
df_train["GarageFinish"] = df_train["GarageFinish"].fillna("No Garage")
df_train["GarageQual"] = df_train["GarageQual"].fillna("No Garage")
df_train["GarageCond"] = df_train["GarageCond"].fillna("No Garage")

# Pool
df_train["PoolQC"] = df_train["PoolQC"].fillna("No Pool")

# Fence
df_train["Fence"] = df_train["Fence"].fillna("No Fence")

# MiscFeature
df_train["MiscFeature"] = np.where(df_train["MiscVal"] == 0, "No misc", df_train["MiscFeature"])

# BrkFace é a categoria mais condizente para essas áreas entre 288 e 312
df_train.loc[[624, 1300, 1334], 'MasVnrType'] = 'BrkFace'

# Como "No masonry" é o mais comum, os outros valores ausentes ficaram assim
df_train["MasVnrType"] = df_train["MasVnrType"].fillna("No masonry")

# O resto das áreas assumiu valor zero
df_train["MasVnrArea"] = np.where(df_train["MasVnrType"] == "No masonry", 0, df_train["MasVnrArea"])

# Agora sim acabaram-se os nulos
nulos = df_train.isna().sum()
print(nulos[nulos > 0])

outliers = df_train[df_train["SalePrice"] > 500000]

# Tirando só os valores maiores que 500000
df_train = df_train.drop(outliers.index)


import streamlit as st
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

# Treina o modelo
y = df_train["SalePrice"]
x = df_train[["GrLivArea","GarageCars","OverallQual"]]

preprocess = ColumnTransformer(
    transformers=[
        ("num", MinMaxScaler(), x.columns)
    ]
)

model = Pipeline(
    steps=[
        ("preprocess", preprocess),
        ("regressor", LinearRegression())
    ]
)

model.fit(x, y)

# Interface
st.title("Previsão de Preço")

area = st.number_input("Área de vivência (em pés)")
garagem = st.number_input("Quantia de carros que cabem na garagem")
qualidade = st.slider("Qualidade da casa",1,10,5)

if st.button("Prever"):

    entrada = pd.DataFrame({
        "GrLivArea":[area],
        "GarageCars":[garagem],
        "OverallQual":[qualidade]
    })

    preco = model.predict(entrada)

    st.write(f"Preço previsto: $ {preco[0]:,.2f}")

# streamlit run C:\Users\eduqu\Downloads\cati.py
